version: "3.3"

services:
    server:
      build:
        context: .
      ports:
        - "5000:5000"
      depends_on:
        - mongo

    mongo:
      image: mongo:4.4
      env_file: ./.env
      ports: 
        - 27017:27017
      environment:
        - MONGO-INITDB_ROOT_USERNAME=$MONGO_USERNAME
        - MONGO-INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      stdin_open: true

 